name: CI
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.x
      - name: Install dependencies
        run: |
          yarn
      - name: Deploy Sanity
        env:
          SANITY_AUTH: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: |
          # Make sure to add a secret for SANITY_AUTH_TOKEN
          "$SANITY_AUTH" yarn sanity deploy
